services:
  redis:
    image: redis:7-alpine
    container_name: employee-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  nexus:
    image: sonatype/nexus3:latest
    container_name: employee-nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped

volumes:
  nexus-data:
